kubecolor/kubecolor

- command/subcommand.go
- kubectl/subcommand.go
It works similarly to the "exec" or "run" subcommands in that it spawns a shell in a pod, so shouldn't be handled by kubecolor as it otherwise mangles the output.
> Don't color the "debug" subcommand

- Dockerfile
Sets the opencontainers labels.
These are required for GH container registry to correlate images with repositories.
Added `LABEL` statements to Dockerfile
> Set Docker labels

- .dockerignore
- .github/workflows/publish_docker_image.yml
- Dockerfile
Changes to the Dockerfile.
- Added .dockerignore to make better use of the caching
- Added extra step with `go mod download` to cache the dependencies separately
- Added build arg to supply the version
- Added kubectl to image (by copying from the bitnami/kubectl image)
- Changed to distroless nonroot image
Various improvements to the Docker image.
Kubectl is a nice to have here, as kubecolor quite heavily relies on it.
> Docker version and non-root

- internal/bytesutil/bytesutil.go
- internal/bytesutil/bytesutil_test.go
- printer/kubectl_describe.go
- scanner/describe/describe.go
Table detection had faulty logic, resulting in inconsistent coloring.
| Before | After |
| --- | --- |
| ![image](https://github.com/kubecolor/kubecolor/assets/2477952/0bb6bcec-c5d1-4fa0-9bc5-844b55c9a4d5) | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/dd1b2e17-5b6f-4688-ad16-de82a45b4d70)
- Moved some `[]byte` handling to new `internal/bytesutil` package
- Fixed "too many columns" detection to not get confused by lots of spaces in the same cell spacer
- Fixes issue with coloring
> Fixed describe table detection

- .github/workflows/test.yml
- scanner/describe/describe_test.go
Don't know why the tests were disabled, but my suspision is because of the Codecov part?
Maybe it'd be nice with a bunch of linting as well, but at this point let's just get some basic testing going first.
- Enable Go test workflow
- Removed Codecov integration.
- Ignore paths, such as markdown files. Don't need to run tests just for typo changes
- Fixed test that was failing on Windows due to EOL (CRLF vs LF)
We do have tests, but we're not running them on every PR.
> Enable Go test workflow

- printer/kubectl_output_colored_printer.go
Having no coloring on OK status is a design choice, but I think its better to enhance it with green coloring.
|  | | 
| --- | ---
| Before | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/7a5694c7-e713-42bf-aea3-fad319da8d66)
| After | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/589ac8dd-60fe-4f76-9eea-a90cc68e17b5)
| |
| Before | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/27b7ca80-ef64-44f5-92d6-7060609461c8)
| After | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/76ba2bbd-433f-4e42-926d-ac1788344a99)
- Added more statuses to be colored
- Added green coloring on OK statuses (nothing was colored green before)
In certain cases, this makes a it much easier to read
> Added green status coloring

- printer/kubectl_describe.go
The describe output has some room for improvement.
Colorizing the statuses is certainly a nice start.
This makes use of the describe path that I teased about in #21, and the screenshots show coloring introduced in the (not yet merged) #25
| Before | After |
| --- | ---
| ![image](https://github.com/kubecolor/kubecolor/assets/2477952/9e789974-56d0-4a27-b506-cf3f5143beea) | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/3f2bb9c2-4629-4a5f-8bd2-c2e31f23e9b4)
- Added status coloring on describe in certain cases, mostly just container status
More colors :)
> Colorize some describe statuses

- internal/bytesutil/bytesutil.go
- printer/kubectl_describe.go
- printer/kubectl_describe_test.go
- printer/kubectl_output_colored_printer_test.go
- printer/table.go
- printer/table_test.go
- scanner/tablescan/tablescan.go
- scanner/tablescan/tablescan_test.go
This PR takes a very similar approach to the describe parser (#21), but has some other hacks such as buffering the tables so that even header-less tables like this has its columns properly indexed:
```
pod-apple            Running                      250d
pod-bear    0/10                 12 (3d ago)
pod-c       2/2      Error       0                13d
```
These lines above are all combined into this:
```
pod-ceare   2/20     Errorng     02 (3d ago)      13dd
```
And then finding columns is run on that combined row.
Some previews of where this PR (as a whole) makes a difference:
| | Get pods (no change) |
| --- | --- |
| Before | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/93c1895c-712d-4a38-ad87-f3a89cd411af)
| After | …
> Redesign table parsing

- printer/kubectl_output_colored_printer.go
fix hard coded color for help messages
fixes #36
> fix hard coded color for help messages

- .github/workflows/release.yml
- Dockerfile
- go.mod
Go 1.21.6 has been released.
Contains only backported fixes, but some good fixes nonetheless: <https://github.com/golang/go/issues?q=milestone%3AGo1.21.6+label%3ACherryPickApproved>
No vulnerability fixes in this release.
- Changed from Go 1.21 to Go 1.21.6 in go.mod & Dockerfile
- Changed GitHub Action to take Go version from go.mod
Stay up-to-date.
Especially the "excessive memory usage" bug
> Update to Go 1.21.6

- internal/ctxscanner/ctxscanner.go
- printer/kubectl_apply_test.go
- printer/kubectl_output_colored_printer.go
- printer/table.go
- scanner/tablescan/tablescan.go
PR #29 introduced a bug that causes `kubectl get pods --watch` to stop working.
The issue is that the new table scanner tries to buffer the entire table to be able to handle gaps in the table when figuring out where columns are. When using `--watch`, the underlying `bufio.Scanner` just freezes, as the output has not reached an EOF. As far as I can find, there's no way to detect if the `io.Reader` is waiting for data or has data available to be read. Would be nice with a `TryScan`/`TryRead`, but alas.
Instead I went for a timeout approach, where it times out after 50ms (perceived as near-instant), by using `context.WithTimeout`
- Added package `internal/ctxscanner`, a wrapper around `bufio.Scanner` that allows a `context.Context` in the scan …
> Fix tablescan freezing

- README.md
PR #40 added `<picture>` element to the README file.
But the `<img width="" height="">` attributes cause some unwanted resizing. It doesn't keep the aspect ratio when getting downsized.
| Before | After this PR |
| --- | ---
| ![image](https://github.com/kubecolor/kubecolor/assets/2477952/de9415fb-1ae1-4c06-9153-79aaa50b7fef) | ![image](https://github.com/kubecolor/kubecolor/assets/2477952/ce7c8a87-2c16-4beb-9ea8-c5b005160f9b)
- Updated README
Looks weird.
No need to create a new release for this. It's just docs
> README: Remove width & height attributes

- README.md
More repositories that the user might be interested in.
- Added Scoop and Nixpkgs install docs to README
- Simplified headers for install docs
The PR to add kubecolor to the Main Scoop bucket was just merged: <https://github.com/ScoopInstaller/Main/pull/5425>
Also, in Nixpkgs it has started to get updated as well: <https://github.com/NixOS/nixpkgs/pull/279307> (only to 0.2.0 so far, but the automatic update actions they have plus ivankovnatsky being quite active should result in 0.2.1 being updated soon too)
Closes #27
> Added Scoop and Nix repo

- printer/kubectl_describe.go
- printer/kubectl_describe_test.go
Regression from the new describe scanner. Forgot to print the table at the end, if there was one buffered up.
- Fixed issue in `printer.DescribePrinter` where it forgot to print a trailing table
Invalid output on commands such as:
```bash
kubectl describe pod my-pod
kubectl roles cert-manager:leaderelection
```
Closes #48, closes #49
> Fix missing trailing table in kubectl describe

- README.md
The AUR package was updated just hours ago: <https://aur.archlinux.org/cgit/aur.git/log/?h=kubecolor>. Let's include it in the README.
Also lets include some badges from Repology, where possible (<https://repology.org/project/kubecolor/versions>). The badges from them turn red when the package is outdated. However Repology does not include some repos (like our Homebrew tap or the Scoop main bucket), so I resorted to using shields.io for those.
- Updated README
More ways for users to install kubecolor
> Added note on AUR package to README

- printer/format.go
- printer/kubectl_describe.go
- printer/kubectl_describe_test.go
- printer/kubectl_output_colored_printer.go
Fix `kubecolor get pod` not show `OOMKilled` with color
fix `kubecolor describe pod` not show condition with color
> Color status for `OOMKilled` and `<nil>`

- Dockerfile
- go.mod
New version of Go just dropped yestarday :tada:
- Updated to Go 1.22
Stay up-to-date.
As kubecolor is an application and not a library, then we have the liberty to stay up-to-date. Thanks to Go's auto-updating forward-compatability feature introduced in Go 1.21, the minimum Go version required is still 1.21.
> This PR is marked as draft because the Docker image for golang:1.22 on amd64 [is not yet available](https://hub.docker.com/r/amd64/golang/tags?page=1&name=1.22.0).
> Update to Go 1.22

- printer/kubectl_apply.go
- printer/kubectl_apply_test.go
The output from `--dry-run=client` and `--dry-run=server` differs.
Before:
After:
- Rewrote the logic behind `printer/kubectl_apply.go`
- Added case for `(server dry run)`
Bugfix
Closes #57
> Fix output from 'apply --dry-run=server'

- README.md
PowerShell completion was always absent from the docs. Until now :)
- Changed references like "config file" to have examples like "e.g `~/.bashrc`"
- Added docs on PowerShell completion
A lot of people are using PowerShell. Possible a lot are also using kubecolor.
I'd assume that most people have found a way around this anyway, but it'd be nice with some official docs to not have users wasting time digging for answers.
Closes #10
> Added docs on PowerShell completions

- README.md
Kubecolor works fine with `oc` as well as `kubectl`, as we noticed in #63
- Added note to README about `alias oc=kubecolor`
Show users up front that we support `oc` as well
Closes #64
> Added docs on `oc` usage

- config/color.go
- config/theme.go
- printer/table.go
Fixes some issues that were partially introduced in #59
- Fixed color cycle adjustment flipping the wrong order when first column is `NAMESPACE`
- Fixed parsing of when color string contains `none` field
- Fixed wrong default color for commands
Fixes some regressions.
> Fix some coloring issues from the coloring PR

- Dockerfile
- go.mod
- go.sum
Update Go. The new Go release is for some vulnerabilities, but `govulncheck` does not mark our codebase as being vulnerable. So this update is not strictly necessary. Though, it's nice to stay up-to-date.
- Updated Go to 1.22.1
Stay up-to-date
> Update to Go 1.22.1

- README.md
- config/preset.go
- config/theme.go
One of the first issues on this repo was that the color scheme changed (#4). 
The coloring is not identical in some areas such as `kubectl describe`, but it's close enough. Can't get 100% old scheme as a lot of parsing is done differently now.
- Added color schemes from the pre-0.0.21/hidetatz version
For people coming from hidetatz's kubecolor then this is a big change. This PR adds back that color scheme, in case they really liked it.
Relates to #4
> Added pre-0.0.21 color preset

- .github/workflows/publish_docker_image.yml
- .github/workflows/test.yml
Removes the pushing of Docker images on each merge.
- Removed pushing to GitHub Container Registry on each merge
- Added building (but not pushing) Docker image on pull requests
The Docker image is not our main delivery source, and I doubt many are running kubecolor in things like docker-compose or Kubernetes.
We can keep the tagged versions, but I propose we skip the (quite noisy) per-merge pushes. Just see for yourself: <https://github.com/kubecolor/kubecolor/pkgs/container/kubecolor/versions?filters%5Bversion_type%5D=tagged>
This also adds the building step, so we can ensure that the Docker image would be successfully built after a PR.
> Skip pushing Docker image for each merge

- README.md
Docs on running via Docker, as well as mounting the `~/.kube/config` (and upcoming `~/.kube/color.yaml`) correctly
- Updated README
Our Docker image has existed for a while, but we haven't really made use of it.
GitHub says that the `v0.2.2` Docker image has been downloaded like 48 times, but my guess is that's only by automated bots trying to scan for vulnerabilities or something. I don't expect we have that much traffic of people using the Docker image when we don't even have docs on it.
> Added docs on running via Docker

- Dockerfile
The docker image was failing:
```console
$ podman run --rm -it -v $HOME/.kube:/home/nonroot/.kube:ro ghcr.io/kubecolor/kubecolor get pods
kubecolor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kubecolor)
kubecolor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kubecolor)
```
According to the distroless example, they seem to suggest disabling CGO: <https://github.com/GoogleContainerTools/distroless/blob/main/examples/go/Dockerfile>
- Disabled CGO in Docker build
- Switched to static-debian distroless base image
Fixes not being able to run the Docker image.
> Fix GLIBC_2.34 version error in Docker image

- config-schema.json
- config/theme.go
- printer/format.go
Durations (3d12h) and quantities (5Gi) have been lacking colors.
- Added color matching on duration and quantity
- Also treat invalid as null
Clearer to see values like resource requests and limits in outputs like `kubectl describe`
Closes #72, closes #73
> Colorize duration & quantity

- README.md
You can now install an Android-specific build of Kubecolor on Termux.
- Added note on installing via Termux to README.md
- Updated badge links on other packages in README.md
People on Android need a specific Android build of Kubecolor. This is now available.
Closes #71, closes #69
> Kubecolor is now available on Termux (Android)

- .github/workflows/govulncheck.yml
- Dockerfile
- go.mod
govulncheck just reported that we need to upgrade to Go 1.22.2 due to vulnerability:
```console
$ govulncheck ./...
Scanning your code and 226 packages across 29 dependent modules for known vulnerabilities...
=== Symbol Results ===
Vulnerability #1: GO-2024-2687
HTTP/2 CONTINUATION flood in net/http
More info: https://pkg.go.dev/vuln/GO-2024-2687
Standard library
Found in: net/http@go1.22.1
Fixed in: net/http@go1.22.2
Example traces found:
#1: testutil/heredoc.go:21:32: testutil.NewHereDocf calls strings.Replacer.Replace, which eventually calls http.CanonicalHeaderKey
#2: config/config.go:57:26: config.LoadViper calls viper.Viper.ReadInConfig, which eventually calls http.bodyEOFSignal.Read
#3: internal/cmd/configschema/main.go:122:14: configschema.main calls fmt.Fprintln, which eventually …
```
> Update Go to 1.22.2

- command/config.go
- command/runner.go
- internal/bytesutil/bytesutil_test.go
Adds a new flag: `--kubecolor-stdin`
Can be used as:
```bash
kubectl get pods > kubectl-output.txt
cat kubectl-output.txt | kubecolor get pods --kubecolor-stdin
kubecolor get pods --kubecolor-stdin=./kubectl-output.txt
```
- Added flag for setting stdin source
Makes it easier to debug kubecolor. It's a quite simple change, but can be quite useful when debugging
Closes #94
> Added flag `--kubecolor-stdin` to allow piping in output

- README.md
Homebrew PR was merged: https://github.com/Homebrew/homebrew-core/pull/166705
The package is also available on Homebrew Formulae: https://formulae.brew.sh/formula/kubecolor
- Updated Homebrew docs in README
This does not remove the custom brew tap in `.goreleaser.yml`. Anyone still using that might want to keep getting updates.
Closes #54
> Kubecolor is now available on homebrew-core

- .goreleaser.yml
Disables CGO in goreleaser, as CGO adds dependencies on host libraries like specific version of glibc.
I noticed this because I was using kubecolor in GH Actions at work, and all of the sudden they stopped working because v0.3.0 was released and we were targeting 'latest' :)
- Added `CGO_ENABLED=0` env var to goreleaser builds
Depending on specific glibc versions means only some people can run the binaries.
Disabling CGO does increase the binary size a bit, but it also makes it self-contained with no host dependencies.
Closes #104
> Disable CGO in release binaries

- command/subcommand.go
- kubectl/subcommand.go
Was looking into #111, where the user had issues using `alias k='kubecolor --force-colors'`.
There were 2 things going wrong here:
- It parsed `kubecolor __complete get` as `command=get` instead of `command=__complete`
- Turns out that `--force-colors` had precedence over if command is marked as "colors unsupported"
- Fixed  `--force-colors` having higher precedence than `isColoringSupported()`
- Fixed parsing of `__complete` subcommands
Resolves edge cases where users use `alias k='kubecolor --force-colors'`
Closes #111
> Fixed kubecolor adding colors in completions

- command/config.go
- command/config_test.go
The `KUBECOLOR_LIGHT_BACKGROUND` variable is working in reverse:
What we should have is:
What we have:
`KUBECOLOR_LIGHT_BACKGROUND=false` should be dark:
`KUBECOLOR_LIGHT_BACKGROUND=false` should be light:
but we have the opposit :)
switched the default color theme when changing the `KUBECOLOR_LIGHT_BACKGROUND` variable
because it's a bug :)
> KUBECOLOR_LIGHT_BACKGROUND was working in reverse

- .github/workflows/release.yml
Adding automation to open a PR on the [Homebrew-core](https://github.com/Homebrew/homebrew-core/) project 
added a second job in the release pipeline that will execute after `go-releaser` is done generating the new release.
it's automation and it's good
> adding automation for HomeBrew update

- command/subcommand_test.go
- kubectl/subcommand.go
- kubectl/subcommand_test.go
Fixes detection of `oc rsh`. Kubecolor was properly configured to not colorize the command, but it was not configured to detect that `oc rsh` was the "Rsh` subcommand.
Silly derp from me when I tried fixing this before in #117
- Added `oc rsh` subcommand detection
- Added tests for subcommand detection
Fixes bug
Closes #108
> Fix detection of 'oc rsh'

- .gitignore
- README.md
- command/config.go
- command/config_test.go
- command/runner.go
- config-schema.json
- config/config.go
- config/config_test.go
- config/paging.go
- coverage.txt
- internal/cmd/configschema/main.go
- kubectl/subcommand.go
Pipe the output of the `get` and `describe` subcommands to a pager.
Example usage:
```
PAGER="less -RF" ./kubecolor --pager get po -A
```
I have only tested this on Linux. I'm hoping someone else can test on Windows.
> feat: pipe through pager

- command/runner.go
Fixes a corner case with the PAGER integration from #122 when no `less` or `more` are installed.
Treat empty pager config as if pager is disabled.
One main place where `less` and `more` are not available is our Dockerfile.
> bugfix: Skip pager integration if no default can be found

- README.md
- command/subcommand.go
- config-schema.json
- config/color.go
- config/color_test.go
- config/theme.go
- kubectl/subcommand.go
- kubectl/subcommand_test.go
- printer/help.go
- printer/kubectl_explain.go
- printer/kubectl_output_colored_printer.go
Colorizes the help pages a bit more.
It contains a very rudamentary shell parser. It parses just enough to be able to colorize the code examples in the kubectl commands that I've tried.
- Added colorization of `--help` output
- Added SupportsColoring method
- Fixed where `kubectl exec --help` nor `kubectl create --help` did not get colorized
- Removed unused subcommands (ctx & ns)
Makes them easier to read.
Closes #75
> Added colorization of help text

- README.md
- command/config_test.go
- command/runner.go
- config-schema.json
- config/color_raw.go
- config/config.go
- config/paging.go
- kubectl/subcommand_test.go
Sorry @lennartack, but me and @prune998 has decided to change paging to opt-in/disabled by default instead of opt-out/enabled by default.
This also means that we don't need a release canidate for our next release.
- Changed `paging` default from `auto` to `never`
- Ran `go fmt`
- Updated docs
It was too intrusive of a change to add pager support by default.
> Changed PAGER feature to opt-in

- .github/workflows/test.yml
- Makefile
Improves the GitHub Action logs a little by using [gotestsum](https://github.com/gotestyourself/gotestsum).
- Added way to override `go test` cmd in `Makefile`
- Changed to use gotestsum in GH Action `.github/workflows/test.yml`
The `go test -v ./...` logs are so verbose and barely readable. Gotestsum does a great job in using colors to make it easy to see when stuff ain't working as it should.
> Change to `gotestsum` in GitHub Actions

- kubectl/subcommand.go
`api-versions`, `api-resources`, `config`
It looks like all of these are safe at the moment and a pager is useful for them
> Add some subcommands to SupportsPager

- .github/workflows/go_version.yml
Adds GitHub Actions workflow for ensuring the version in go.mod remains the same as in the Dockerfile.
- N/A
- Added workflow
Makes it so we don't forget to change the version in both locations.
> Added workflow for linting Go version in go.mod vs Dockerfile

- Dockerfile
- go.mod
Updates Go from 1.22.2 to 1.22.5
- N/A
- Changed version in go.mod
Stay up to date with latest patches from the Go stdlib
> Update to Go 1.22.5

- config/config.go
Simple change. Must've been a regression from some refactor.
- Fixed debug log not being inside a `if v.GetBool("debug")`
Too much logging
> Fixed debug log of missing config file always printing

- Dockerfile
Fixes the following warning:
> **The 'as' keyword should match the case of the 'from' keyword**
>
> ```
> FromAsCasing: 'as' and 'FROM' keywords' casing do not match
> More info: https://docs.docker.com/go/dockerfile/rule/from-as-casing/
> ```
- Fixed linting issue in Dockerfile
Resovle the warning that's shown in PRs
> Fix linting issue in Dockerfile

- config/color.go
- printer/kubectl_describe.go
- printer/kubectl_output_colored_printer.go
- printer/table.go
- printer/util.go
- test/corpus/table.txt
Coloring multiple statuses.
| Before | After
| ------ | -----
| ![before screenshot of test/corpus/table.txt](https://github.com/user-attachments/assets/c403c253-f27d-4f1b-aa67-f3097f848433) | ![after screenshot of test/corpus/table.txt](https://github.com/user-attachments/assets/a6912644-feba-4925-be9c-58ba0db17b92)
- Changed code so TablePrinter's callback can modify full string
- Fixed Color.Render so it doesn't inject colors when full string is colored.
- Added coloring of `SchedulingDisabled` node status
Make it clearer when you have multiple statuses on a resource.
Closes #146
> Colorize multiple statuses (e.g node `Ready,SchedulingDisabled`)

- config-schema.json
- config/theme.go
- printer/kubectl_output_colored_printer.go
- test/corpus/kubectl_scale.txt
Colorizing `kubectl scale`
- Added coloring for `kubectl scale`
More colors :D
> Colorize kubectl scale

- internal/cmd/configdoc/print_yaml.go
Changed (and bugfixed) the configdoc script.
- Docs needs to be regenerated (already in use in <https://github.com/kubecolor/kubecolor.github.io/pull/8>)
- Added tabwriter to YAML printer to make comments line up with each other
- Fixed some fields having wrong naming (e.g `durationfresh` -> `durationFresh`, `dryrun` -> `dryRun`). The naming implementation was copied from the JSON schema generator's naming function.
The tabwriter makes it more readable, and the naming fixes makes it match up with the JSON schema.
Viper (the config library) doesn't care about casing in YAML fields, so using all lowercase still _works_
> Updated config reference docs generation

- config-schema.json
- config/theme.go
- printer/stderr.go
- test/corpus/stderr.txt
Changes the fallback on stderr printer from single-colored default color, to instead use the LogsPrinter.
- deprecated a config field
- Changed StderrPrinter to make use of LogsPrinter
- Changed Config.Stderr.Default field to "deprecated"
Better coloring
Closes #165
> Colorize stderr logs using "kubectl logs" logic

- scanner/logscan/logscan.go
- scanner/logscan/logscan_fuzz_test.go
- scanner/logscan/logscan_test.go
- scanner/logscan/testdata/fuzz/FuzzScanner/46fe09268915aa91
- scanner/logscan/testdata/fuzz/FuzzScanner/771e938e4458e983
- scanner/logscan/testdata/fuzz/FuzzScanner/ff7bb51f08e94b47
Fixes some log lines not being the same output as input. I tried out fuzz testing for the first time, and I can say I've quite enjoyed it.
All issues the fuzz testing found after running for a few milliseconds. After all the fixes in this PR, I let the fuzz testing run for an hour. On my 32-cores desktop while running at 100% CPU usage for a full hour it tried out 801 490 513 different inputs during, and still didn't find any more troublesome inputs:
```console
$ go test -fuzz FuzzScanner ./scanner/logscan/
fuzz: elapsed: 0s, gathering baseline coverage: 0/234 completed
fuzz: elapsed: 0s, gathering baseline coverage: 234/234 completed, now fuzzing with 32 workers
fuzz: elapsed: 3s, execs: 297125 (99036/sec), new interesting: 39 (total: 273)
fuzz: elapsed: 6s, execs: 473868 (58906/sec), …
```
> Fixed logs parsing

- scanner/logscan/logscan.go
- scanner/logscan/logscan_test.go
* since `+02:00` was highlighted as time, `-05:00` should also be
highlighted as part of a timestamp
- Changed `dateRegex` to also accept negative TZ offsets
- Add test case for `-0500`
We highlight `+02:00` but not `-0500`
> allow negative tz offsets in time regex

- Dockerfile
- go.mod
Updates Go to latest v1.22 release to resolve vulnerabilities:
- Stack exhaustion in Parse in go/build/constraint: https://pkg.go.dev/vuln/GO-2024-3107
- Stack exhaustion in all Parse functions in go/parser: https://pkg.go.dev/vuln/GO-2024-3105
These vulnerabilities only affect our internal generator commands (`./internal/cmd/configschema` & `./internal/cmd/configdoc`), so it's not super urgent.
- Changed version in go.mod
- Changed version in Dockerfile
Stay up to date and do not ship vulnerabilities
Closes #175
> Update to Go 1.22.7

- printer/kubectl_version.go
Fixes the indentation of `kubectl version -o yaml`. The original kubectl output uses 2 spaces for indentation, but in v0.4.0 we accidentally changed it to 4 spaces when doing the "kubecolor version injection".
- Fixed YAML indentation of `kubectl version -o yaml` of being 4 instead of 2
Bug.
This wouldn't appear in any scripts as kubecolor is only doing this when it can also apply colors, so any scripts that do weird stuff like "read the N'th line and then skip 2 spaces" didn't get affected anyways. This is just a visual thing
no issue
> Fixed 'kubectl version -o yaml' indentation

- scanner/logscan/logscan.go
- test/corpus/kubectl_logs.txt
Some loggers use `DEBU` for debug logs. Common approach when they want all log levels to have the same width:
```
DEBU
INFO
WARN
ERRO
```
- Fixed `DEBU` not being recognized as a debug log level
- Added `DEBUGGING` as log level too, just in case
Was wrongly colored. I had logs like these:
```
DEBU server.distmemorystore.olric: Failed to find 172.23.109.6:3320 in the cluster: member not found
```
It should've seen `DEBU` at the start and color it gray. But instead, it found `Failed` and then colored that red.
> Fixed 'DEBU' not being read as debug log level

- config-schema.json
- config/theme.go
- internal/stringutil/stringutil.go
- internal/testcorpus/scanner.go
- printer/kubectl_diff.go
- printer/kubectl_output_colored_printer.go
- test/corpus/kubectl_diff.txt
- Added Printer for `kubectl diff`
- it will render added lines as addition
- and removed lines as deletion
- untouched lines are rendered as ignored
View Issue #190 
Closes #190
> Feat: Adding color-rendering for kubectl diff

- Dockerfile
- go.mod
Updates Go to 1.23.4
- Changed version in Dockerfile
- Changed version in go.mod
Stay up-to-date, also #205 requires Go 1.23.0 or later
none
> Update Go to 1.23.4

- config-schema.json
- config/theme.go
- printer/kubectl_output_colored_printer.go
- test/corpus/kubectl_apply.txt
Adds missing colorization on `kubectl apply --server-side`
- Added coloring of verb `serverside-applied`
More colors. It was just green before.
Closes #194
> Colorize `kubectl apply --server-side`

- Dockerfile
- go.mod
Updates Go for the sake of resolving vulnerabilities:
- "Timing sidechannel for P-256 on ppc64le in crypto/internal/nistec" https://pkg.go.dev/vuln/GO-2025-3447
- "Usage of IPv6 zone IDs can bypass URI name constraints in crypto/x509" https://pkg.go.dev/vuln/GO-2025-3373
These vulnerabilities originate from `strings.Replacer.Replace`, which we use. But we don't do any auth or anything security related so these vulnerabilities don't really apply to us.
Let's still update though just to silence the security alerts.
- Changed Go version in go.mod & Dockerfile
Stay up-to-date & resolve govulncheck alert
Closes #213
> Update to Go 1.23.6

- Dockerfile
- go.mod
- kubectl/subcommand_test.go
Updated Go to resolve vulnerabilities:
```console
$ govulncheck ./...
govulncheck: loading packages: 
There are errors with the provided package patterns:
/home/runner/go/pkg/mod/golang.org/x/sys@v0.29.0/unix/vgetrandom_linux.go:7:9: file requires newer Go version go1.24 (application built with go1.23)
For details on package patterns, see https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns.
```
- Changed version of Go in `go.mod` & `Dockerfile`
Keep it up-to-date, and to resolve vulnerability
Closes #226
> Update Go to 1.24.2

- .github/workflows/release.yml
- .goreleaser.yml
Changes our `release.yml` workflow to trigger when a release is created (as a draft), and let goreleaser populate the release with binaries/archives and then publish the release for us.
- Changed goreleaser to try reuse a draft release if it finds one
- Changed `release.yml` workflow to trigger on draft release instead of on new tag
A big pain point with automated continuous delivery is when the pipelines break.
Imagine, with the old workflow:
1. you create a tag v0.5.0
2. the goreleaser pipeline failed
3. you push a fix to the goreleaser pipeline
4. you have to create a new tag, e.g v0.5.1
5. maybe repeat step 2-4 a couple of times, so you end up at version v0.5.7
6. all of our users get super confused why we just jumped from v0.5.0 to v0.5.7
This is super annoying and has happened to us …
> Use draft releases when releasing new versions

- .github/workflows/release.yml
Fixes the release.yml workflow
- Fixed `git tag` not knowing who the Git author is
I tried making a release and the workflow failed: https://github.com/kubecolor/kubecolor/actions/runs/14617603904/job/41009349352
The "Try to create tag" step failed.
> Fix git tagging in release workflow

- .github/workflows/release.yml
Fix
- Fixed missing `GH_TOKEN` env var for the `gh` CLI in release.yml workflow
Failed: <https://github.com/kubecolor/kubecolor/actions/runs/14618868576/job/41013589477>
> Fix upload assets to release

- printer/util.go
I got curious after seeing issue #254 and I implemented colorizing for missing error status.
I didn't manage to get the `StartError` status mentioned but I accidentally got `ContainerCannotRun` which wasn't implemented either.
I also added `DeadlineExceeded` and `RunContainerError` as I found these mentioned in other repos. I haven't been able to find a documented list with all the possible reasons as it seems to depend heavily on the CRI used.
Before:
After:
For anyone interested, I got this error by creating a pod with a fake command like this:
```bash
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
name: test
spec:
containers:
- name: busybox
image: busybox:latest
command: ["/bin/this-command-does-not-exist"]
restartPolicy: Never
EOF
```
- Added new error status
More …
> Add missing error status colorizing

- Dockerfile
- go.mod
- go.sum
Updates mapstructure & Go to fix vulnerabilities reported by govulncheck:
```console
$ govulncheck ./...
=== Symbol Results ===
Vulnerability #1: GO-2025-3787
May leak sensitive information in logs when processing malformed data in
github.com/go-viper/mapstructure
More info: https://pkg.go.dev/vuln/GO-2025-3787
Module: github.com/go-viper/mapstructure/v2
Found in: github.com/go-viper/mapstructure/v2@v2.2.1
Fixed in: github.com/go-viper/mapstructure/v2@v2.3.0
Example traces found:
#1: config/config.go:94:23: config.Unmarshal calls viper.Viper.Unmarshal, which eventually calls errors.As
#2: config/config.go:94:23: config.Unmarshal calls viper.Viper.Unmarshal, which eventually calls errors.Join
#3: config/config.go:94:23: config.Unmarshal calls viper.Viper.Unmarshal, which eventually calls …
```
> Update Go v1.24.0 -> v1.24.5 & mapstructure v2.2.1 -> v2.4.0 to fix vulnerability

- Dockerfile
- go.mod
Updates Go
- Changed Go version in go.mod from 1.24.5 to 1.24.7
Resolve vulnerability https://pkg.go.dev/vuln/GO-2025-3956 / CVE-2025-47906
Closes #270
> Update Go to 1.24.7 to fix vuln GO-2025-3956 / CVE-2025-47906

- .github/workflows/release.yml
Fixes the release pipeline
- Fixed [actions/download-artifact](https://github.com/actions/download-artifact) action
We recently updated it from v4 to v5 and this broke the release pipeline, because they changed the destination path of the downloaded artifacts.
> Fix release workflow after actions/download-artifacts update
